/**
 * TS mirror of `vdf_core::geometry::Affine2`.
 *
 * The compositor (M1) will transform geometry on the GPU using matrices
 * handed over from Rust; this mirror exists so both sides are verified
 * against the same golden vectors (tests/vectors/affine-cases.json,
 * generated by a Rust test) and can never drift silently.
 *
 * Matrix layout and composition order MUST match the Rust side exactly:
 * `[a c e; b d f; 0 0 1]`, `compose(m, other)` = apply `m` first, then `other`.
 */

export interface Affine2 {
  a: number;
  b: number;
  c: number;
  d: number;
  e: number;
  f: number;
}

export const AFFINE_IDENTITY: Affine2 = { a: 1, b: 0, c: 0, d: 1, e: 0, f: 0 };

export function affineApply(m: Affine2, x: number, y: number): [number, number] {
  return [m.a * x + m.c * y + m.e, m.b * x + m.d * y + m.f];
}

export function affineCompose(m: Affine2, other: Affine2): Affine2 {
  return {
    a: other.a * m.a + other.c * m.b,
    b: other.b * m.a + other.d * m.b,
    c: other.a * m.c + other.c * m.d,
    d: other.b * m.c + other.d * m.d,
    e: other.a * m.e + other.c * m.f + other.e,
    f: other.b * m.e + other.d * m.f + other.f,
  };
}

export function affineInvert(m: Affine2): Affine2 | null {
  if (![m.a, m.b, m.c, m.d, m.e, m.f].every(Number.isFinite)) return null;
  const det = m.a * m.d - m.b * m.c;
  if (Math.abs(det) < 1e-12) return null;
  return {
    a: m.d / det,
    b: -m.b / det,
    c: -m.c / det,
    d: m.a / det,
    e: (m.c * m.f - m.d * m.e) / det,
    f: (m.b * m.e - m.a * m.f) / det,
  };
}
