/**
 * Golden-vector conformance test: the TS affine mirror must agree with the
 * Rust implementation to 1e-9 on the cases in tests/vectors/affine-cases.json,
 * which are generated by crates/vdf-core/tests/golden_vectors.rs.
 *
 * If this test fails, the TS mirror drifted from Rust — fix the mirror or the
 * Rust side; never regenerate the vectors to make the test pass.
 */

import { readFileSync } from "node:fs";
import { describe, expect, it } from "vitest";
import {
  AFFINE_IDENTITY,
  affineApply,
  affineCompose,
  affineInvert,
  type Affine2,
} from "./state/affine";

interface VectorCase {
  name: string;
  m: [number, number, number, number, number, number];
  p: [number, number];
  applied: [number, number];
  inverted: [number, number] | null;
  /** m then (translate 10, -4), matching Rust compose check */
  composed: [number, number];
}

interface VectorFile {
  version: number;
  cases: VectorCase[];
}

const path = new URL("../tests/vectors/affine-cases.json", import.meta.url);
const vectors: VectorFile = JSON.parse(readFileSync(path, "utf8"));

function toAffine(m: VectorCase["m"]): Affine2 {
  return { a: m[0]!, b: m[1]!, c: m[2]!, d: m[3]!, e: m[4]!, f: m[5]! };
}

describe("affine golden vectors (Rust ↔ TS conformance)", () => {
  it("file exists and has cases", () => {
    expect(vectors.version).toBe(1);
    expect(vectors.cases.length).toBeGreaterThanOrEqual(6);
  });

  for (const tc of vectors.cases) {
    it(`case: ${tc.name}`, () => {
      const m = toAffine(tc.m);
      const [px, py] = affineApply(m, tc.p[0]!, tc.p[1]!);
      expect(px).toBeCloseTo(tc.applied[0]!, 9);
      expect(py).toBeCloseTo(tc.applied[1]!, 9);

      const inv = affineInvert(m);
      if (tc.inverted === null) {
        expect(inv).toBeNull();
      } else {
        expect(inv).not.toBeNull();
        const [ix, iy] = affineApply(inv!, tc.applied[0]!, tc.applied[1]!);
        expect(ix).toBeCloseTo(tc.inverted[0]!, 9);
        expect(iy).toBeCloseTo(tc.inverted[1]!, 9);
      }

      const composed = affineCompose(m, { a: 1, b: 0, c: 0, d: 1, e: 10, f: -4 });
      const [cx, cy] = affineApply(composed, tc.p[0]!, tc.p[1]!);
      expect(cx).toBeCloseTo(tc.composed[0]!, 9);
      expect(cy).toBeCloseTo(tc.composed[1]!, 9);
    });
  }

  it("identity is neutral", () => {
    const [x, y] = affineApply(AFFINE_IDENTITY, 3.5, -7.25);
    expect(x).toBe(3.5);
    expect(y).toBe(-7.25);
  });
});
